api.autodiscovery.id: "16555442" 
accountsysapi:
  name: "account-sys-api"
  version: "v1"
  http:
    path:
      base: "/v1"
      resource: "/*"
      console: "/console/*"
    port: "8083"

database:
  config:
    host: "4.tcp.ngrok.io"
    port: "16783"
    user: "![1RxDpX+J0qE=]"
    password: "![tMHSiVeFPeg=]"
    name: "customer"
  query:
    accountuserdetail:
      search: 
        all: "SELECT usr.id, acct.username, usrdtl.fullname, usrdtl.birthday, usrdtl.gender, acct.date_registered FROM user usr JOIN account acct ON usr.id=acct.user_id JOIN user_detail usrdtl ON usr.id=usrdtl.user_id WHERE acct.active=1"
        byusername: "SELECT usr.id, acct.username, usrdtl.fullname, usrdtl.birthday, usrdtl.gender, acct.date_registered FROM user usr JOIN account acct ON usr.id=acct.user_id JOIN user_detail usrdtl ON usr.id=usrdtl.user_id WHERE acct.username = :username AND acct.active=1"
    user:    
      insert: "INSERT INTO user(username, first_name, middle_name, last_name, created_datetime) VALUES(:userName, :firstName, :middleName, :lastName, :createdDateTime)"
    account:
      bulk.insert: "INSERT INTO account(user_id, username, active, date_registered, created_datetime) VALUES((SELECT id FROM user WHERE username = :userName), :userName, :active, :dateRegistered, :createdDateTime)"
      insert: "INSERT INTO account(user_id, username, active, date_registered, created_datetime) VALUES(:userId, :userName, :active, :dateRegistered, :createdDateTime)"
    userdetail:
      bulk.insert: "INSERT INTO user_detail(user_id, fullname, birthday, gender, created_datetime) VALUES((SELECT id FROM user WHERE username = :userName), :fullName, :birthday, :gender, :createdDateTime)"
      insert: "INSERT INTO user_detail(user_id, fullname, birthday, gender, created_datetime) VALUES(:userId, :fullName, :birthday, :gender, :createdDateTime)"
  params:
    userdetail:
      gender:
        female: "Female"
        male: "Male"
        f: "F"
        m: "M"  
    account:
      active: "1"
       